### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by reactmore** [PTNUSASATUINTIARTHA-DOKU/jokul-php-example#1]
Jokul sama doku tuh sama atau gimana ya ?

**Comment by ariefrizkyr** [comment]
Hi @reactmore ,

Jokul merupakan Payment Gateway System terbaru dari DOKU.

Ada beberapa kelebihan yang Jokul tawarkan dibandingkan dengan sistem Payment Gateway kami sebelumnya:

1. Easy Integration: Anda bisa langsung mencoba mendaftarkan diri di Sandbox Environment Jokul untuk mencoba kemudahan integrasinya. [Klik di sini untuk mendaftar](https://sandbox.doku.com/bo/login), Anda juga bisa melihat Documentationnya di [sini](https://jokul.doku.com/docs)
2. One Back Office for All: Anda bisa melihat seluruh data transaksi dan data financial secara transparan di dalam satu Back Office

Saat ini Jokul dalam versi Beta dan kami sangat senang bila Anda bisa mencoba Payment Gateway System terbaru dari DOKU untuk mendengar feedback dari Anda.

Terima kasih
