### ISSUE TITLE
Mandiri VA / Mandiri Syariah VA Invalid signature key

### ISSUE THREAD

**Issue by amrullahdev** [PTNUSASATUINTIARTHA-DOKU/jokul-php-example#2]
![image](https://user-images.githubusercontent.com/52965747/116670689-3a356d80-a9ca-11eb-8605-5e431b325f8d.png)

udah di ganti sama client id dan secret key saya , tapi tetap bgini .

**Comment by ariefrizkyr** [comment]
Hi @amrullahdev , boleh diinfokan ini error pada saat proses initiate transaksi ke Jokul atau menerima notifikasi dari Jokul?

Terima kasih.

**Comment by amrullahdev** [comment]
untuk proses nya , 

1. saya git clone
2. composer install
3. jalanin aplikasi
5. gantik shared key dengan cliend id dengan yang punya saya 
4.  pilih mandiri VA 
5.  error signature .

**Comment by ariefrizkyr** [comment]
Kami baru saja update fixing untuk sample projectnya, silakan coba clone ulang project ini dan pastikan untuk menggunakan Jokul PHP Library yang versi `master` kami. https://packagist.org/packages/doku/jokul-php-library#dev-master

**Comment by amrullahdev** [comment]
baik terimakasih mas  atas bantuanya saya close isue ini jika bgitu , sekali lagi terimakasih atas respon dan bantuanya mas
