### ISSUE TITLE
Doku VA | Sandbox refuse to connect

### ISSUE THREAD

**Issue by amrullahdev** [PTNUSASATUINTIARTHA-DOKU/jokul-php-example#3]
tampilan  iframe tidak dapat di munculkan  namun saat saya akses langusng linknya bisa terbuka
![image](https://user-images.githubusercontent.com/52965747/116671998-d744d600-a9cb-11eb-9940-7b16de0a9292.png)

**Comment by ariefrizkyr** [comment]
Hi @amrullahdev , saat ini halaman how to pay URL tidak bisa diakses via iFrame karena akan terkena cross policy.

Secara implementasi, kami sarankan ada 2 opsi:

1. Jika ingin membuat custom tampilan langkah pembayaran, bisa menggunakan `how_to_pay_api`
2. Jika ingin menggunakan halaman how to pay yang Jokul sediakan, bisa menaruh link yang redirect ke halaman `how_to_pay_page`

**Comment by amrullahdev** [comment]
ok makasih mas berarti saya mengunkan view dari apinya saja
